pages:
  stage: deploy

  script:
    - echo "DISABLED -- failes with error 'too large'"
    #- python3 ./gitlab_ci.py

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
