pages:
  stage: deploy

  script:
    - mkdir .public
    - cp robots.txt  sitemap-html-html.txt  sitemap-pdf-html.txt  sitemap-pdf-pdf.txt index.html .public/
    - cp -r html .public/
    - cp -r pdf .public/
    - rm -rf public
    - mv .public public

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
